apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-application
  namespace: spring
  labels: 
    app: frontend
    owner: vaikunth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: spring-image
        image: vaikunths/spring-application:v1.1
        ports:
        - containerPort: 8080