apiVersion: v1 
kind: Service 
metadata:
  name: aws-lb-service
  namespace: spring
  labels:
    app: frontend
spec:
  selector:
      app: frontend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer